environment: development
chdir: /home/beerdy/Dev/github/sleepy
address: 0.0.0.0
user: beerdy
group: beerdy
port: 3000
rackup: config.ru
log: log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false